- name: Preparing for osd node tests
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    osd_group_num: "{{ groups['osd'] | length }}"
    get_osd_script_path: "../../files/get-random-osd.py"
    ceph_client_host: "{{ groups['storage'][0] }}"
    osd_down_precentage: 30
  tasks:
    - name: Random select one osd host
      add_host:
        groups: random_one_osd_host
        name: "{{ groups['osd'] | random }}"
      when:
        - osd_group_num | int >= 1

    - name: Copy get-random-osd.py to storage node
      copy: 
        src: "{{ get_osd_script_path }}"
        dest: /tmp/get-random-osd.py
        mode: 0644
      delegate_to: "{{ ceph_client_host }}"

    - shell: "python get-random-osd.py --get-pg-osd --mgmt-osd 
             --format json --file /tmp/get-pg-osd"
      args:
        chdir: /tmp
      delegate_to: "{{ ceph_client_host }}"
    
    - fetch:
        src: "/tmp/get-pg-osd.json"
        dest: "/tmp/get-pg-osd.json"
        flat: yes
        fail_on_missing: yes
      delegate_to: "{{ ceph_client_host }}"

    - include_vars:
        name: _get_pg_osd
        file: "/tmp/get-pg-osd.json"

    - file:
        path: "/tmp/get-pg-osd.json"
        state: absent

    - name: Select one osd in random PG     
      add_host:
        groups: one_osd_pg_hosts
        name: "{{ item.key }}"
        one_osd_pg_list: "{{ item.value }}"
      with_dict: "{{ _get_pg_osd['items'][0] }}"
      when: _get_pg_osd['size'] >= 1

    - name: Select two osds in random PG 
      add_host:
        groups: two_osds_pg_hosts
        name: "{{ item.key }}"
        two_osds_pg_list: "{{ item.value }}"
      with_dict: "{{ _get_pg_osd['items'][1] }}"
      when: _get_pg_osd['size'] >= 2

    - name: Select three osds in random PG
      add_host:
        groups: three_osds_pg_hosts
        name: "{{ item.key }}"
        three_osds_pg_list: "{{ item.value }}"
      with_dict: "{{ _get_pg_osd['items'][2] }}"
      when: _get_pg_osd['size'] >= 3

    - shell: "python get-random-osd.py --get-random-osd 
             --percentage {{ osd_down_precentage }} --mgmt-osd 
             --format json --file /tmp/get-random-osd"
      args:
        chdir: /tmp
      delegate_to: "{{ ceph_client_host }}"
    
    - fetch:
        src: "/tmp/get-random-osd.json"
        dest: "/tmp/get-random-osd.json"
        flat: yes
        fail_on_missing: yes
      delegate_to: "{{ ceph_client_host }}"

    - include_vars:
        name: _get_random_osd
        file: "/tmp/get-random-osd.json"

    - file:
        path: "/tmp/get-random-osd.json"
        state: absent

    - name: Select some random osds
      add_host:
        groups: random_osd_hosts
        name: "{{ item.key }}"
        random_osd_list: "{{ item.value }}"
      with_dict: "{{ _get_random_osd['items'] }}"

    - name: Absent get-random-osd.py from storage node
      file:
        path: "/tmp/get-random-osd.py"
        state: absent
      delegate_to: "{{ ceph_client_host }}"
  tags:
    - osd-pre


## System Level

- include: ../system/base.yml
  vars:
    random_hosts: random_one_osd_host
    node_group: osd
  tags:
    - system
    - osd
    - osd-system

- include: ../system/nic.yml
  vars:
    random_hosts: random_one_osd_host
    node_group: osd
    nic_type: storage
    nic: "{{ storage_nic_name }}"
  tags:
    - system
    - osd
    - osd-system
    - osd-storage-nic

## Service Level
- include: osd/kill_osd.yml
  vars:
    random_hosts: one_osd_pg_hosts
    osd_down_list: "{{ one_osd_pg_list }}"
  tags:
    - service
    - osd
    - osd-service
    - osd-down

- include: osd/kill_osd.yml
  vars:
    random_hosts: two_osds_pg_hosts
    osd_down_list: "{{ two_osds_pg_list }}"
  tags:
    - service
    - osd
    - osd-service
    - osd-down

- include: osd/kill_osd.yml
  vars:
    random_hosts: three_osds_pg_hosts
    osd_down_list: "{{ three_osds_pg_list }}"
  tags:
    - service
    - osd
    - osd-service
    - osd-down

- include: osd/kill_osd.yml
  vars:
    random_hosts: random_osd_hosts
    osd_down_list: "{{ random_osd_list }}"
  tags:
    - service
    - osd
    - osd-service
    - osd-down

- include: osd/del_osd_partition.yml
  vars:
    random_hosts: one_osd_pg_hosts
    osd_down_list: "{{ one_osd_pg_list }}"
  tags:
    - service
    - osd
    - osd-service
    - osd-partition-del
